# Задание №1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение:__<br>
<p></p>
а) Поскольку число столбцов матрицы $A(2)$ не равно числу строк матрицы $A(4)$, следовательно AB неопределено, а поскольку число столбцов матрицы  $A(2)$ так же не равно числу строк матрицы $A(4)$, следовательно AB также неопределено.<br>
б) AB имеет размер $2x3$ - определено, соответственно BA не определено.<br>
в) AB определено, полученная матрица имеет размер 8х8, BA определено, полученная матрица имеет размер 3х3.<br>
г) AB и BA определены и полученные матрицы имеют размер 4х4.<br>

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение:__<br>
$A=\begin{pmatrix}
1 + 4& -2 + (-1)\\ 
3 + 0& 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [4]:
import numpy as np

A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])
C=np.arange(4).reshape(2,2)
for i in range(len(A)):
    for j in range(len(A[i])):
        C[i][j]=A[i][j]+B[i][j]
C

array([[ 5, -3],
       [ 3,  5]])

In [6]:
print("Проверим с numpy:")

A+B

Проверим с numpy:


array([[ 5, -3],
       [ 3,  5]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$<br>

__Решение:__<br>
<p></p>
 $3A-2B+4C = 3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2* \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4*\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3*1 & 3*7\\ 
3*3 & 3*(-6)
\end{pmatrix} - \begin{pmatrix}
2*0 & 2*5\\ 
2*2 & 2*(-1)
\end{pmatrix} + \begin{pmatrix}
4*2 & 4*(-4)\\ 
4*1 & 4*1\end{pmatrix}$
<p></p>
 $3A-2B+4C = \begin{pmatrix}
 3-0+8 & 9-4+4\\ 
21-10-16 & -18+2+4
\end{pmatrix} = \begin{pmatrix}
 11 & 9\\ 
9 & -12
\end{pmatrix}$
<p></p>
</br>
проверим с numpy:

In [7]:
a=np.array([[1,7],[3,-6]])
b=np.array([[0,5],[2,-1]])
c=np.array([[2,-4],[1,1]])
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__Решение:__<br>
<p></p>
$A^{T}=\begin{pmatrix}
4 & 5&2\\ 
1 & -2&3
\end{pmatrix}$.

$A^{T}A = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 5&2\\ 
1 & -2&3
\end{pmatrix}= \begin{pmatrix}
4*4+1*1 & 4*5+1*-2&4*2+1*3\\ 
5*4+(-2)*1 & 5*5+(-2)*(-2)&5*2+(-2)*3\\2*4+3*1&2*5+3*(-2)&2*2+3*3
\end{pmatrix}=\begin{pmatrix}
17 & 18&11\\ 
18 &29&4\\11&4&13
\end{pmatrix}$.
$AA^{T} = \begin{pmatrix}
4 & 5&2\\ 
1 & -2&3
\end{pmatrix}*\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=\begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*-2+2*3\\
1*4+(-2)*5+3*2& 1*1+(-2)*(-2)+3*3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\0& 14
\end{pmatrix}$

In [8]:
# Функция возвращает транспонированную матрицу
def trans_matrix(matrix):
    trans=np.empty(shape=[matrix.shape[1],matrix.shape[0]])
    for i in range(trans.shape[0]):
        for j in range(trans.shape[1]):
            trans[i][j]=matrix[j][i]
    return trans

Проверим с numpy:

In [9]:
A=np.array([[4,1],[5,-2],[2,3]])
trans_matrix(A)

array([[ 4.,  5.,  2.],
       [ 1., -2.,  3.]])

In [10]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [11]:
A@trans_matrix(A)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [12]:
A@A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [13]:
trans_matrix(A)@A

array([[45.,  0.],
       [ 0., 14.]])

In [14]:
A.T@A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [15]:
def multiplicate_matrix(left,right):
    try: 
        left.shape[1]==right.shape[0]
        result=[]
        temp=[]
        s=0
        for i in range(left.shape[0]):
            for j in range(right.shape[1]):
                for k in range(right.shape[0]):
                    s+=left[i][k]*right[k][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]
        return np.array(result)
    except Exception:
        print('Произведение матриц таких размеров не определено!')

In [16]:
A=np.array([[1,-2],[3,0],[4,1],[6,9]])
B=np.array([[4,-1,3,2],[0,5,2,-5]])

In [17]:
A.dot(B)

array([[  4, -11,  -1,  12],
       [ 12,  -3,   9,   6],
       [ 16,   1,  14,   3],
       [ 24,  39,  36, -33]])

In [18]:
multiplicate_matrix(A,B)

array([[  4, -11,  -1,  12],
       [ 12,  -3,   9,   6],
       [ 16,   1,  14,   3],
       [ 24,  39,  36, -33]])

In [19]:
B.dot(A)

array([[ 25,  13],
       [ -7, -43]])

In [20]:
multiplicate_matrix(B,A)

array([[ 25,  13],
       [ -7, -43]])

# Задание №2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__Решение:__<br>
<p></p>

а) Для матрицы порядка 2:
$A=\begin{pmatrix}
a_{11}&a_{12}\\ 
a_{21}& a_{22}
\end{pmatrix}$</br>
<p></p>
Определитель вычисляется как:
$detA=a_{11}a_{22}-a_{12} a_{21}$
<p></p>
Тогда:</r>
$A=\begin{pmatrix}
sinx&-cosx\\ 
cosx& sinx
\end{pmatrix}$</br>
<p></p>
$detA=sinx*sinx-(-cosx)*cosx=sin^2x+cos^2x=1$

In [21]:
print("Проверим с помощью numpy")
for x in range(0,11,2):
    A=np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
    print(x, round(np.linalg.det(A)))

Проверим с помощью numpy
0 1
2 1
4 1
6 1
8 1
10 1


б) Воспользуемся свойством определителя матрицы треугольного вида:
Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали</b>

$detB=4*5*9=180$


In [22]:
print("Проверим с помощью numpy")
B=np.array([[4,2,3], [0,5,1],[0,0,9]])  
np.linalg.det(B)

Проверим с помощью numpy


180.0

в) Разложим по элементам первой строки:
    $C=\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}.$
<p></p>
$detC=1*\begin{pmatrix}
5 & 6\\ 8 & 9
\end{pmatrix}-2*\begin{pmatrix}
4 & 6\\ 7 & 9
\end{pmatrix}+3*\begin{pmatrix}
4 &5\\ 7&8
\end{pmatrix}=1*(5*9-6*8)-2*(4*9-6*7)+3*(4*8-5*7)=0$

In [23]:
print("Проверим с помощью numpy")
C=np.array([[1,2,3], [4,5,6],[7,8,9]])  
round(np.linalg.det(C),1)

Проверим с помощью numpy


0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение:__<br>
<p></p>
a) Используем следующее свойство определителя:

Для двух квадратных матриц одинакового размера
$det(AB)=detA*detB$</br>
Следовательно:</br>
$det(A^2)=detA*detA=4*4=16$

б) Используем следующее свойство определителя:

Определитель транспонированной матрицы равен определителю исходной:

$det(A^T)=detA=4$

в) Из свойства определителя:

Умножение строки или столбца матрицы на число 𝜆 приведет к умножению определителя матрицы на то же число.

Следует, что $det(2A)=2^n*det(A)=2^n*4$, где n - порядок матрицы A

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение:__<br>
<p></p>
Поскольку мы можем представить вторую строку данной матрицы (4,-14,6) через первую ее строку (-2,7-3) как </br>
$(4,-14,6)=-2*(-2,7-3)$, т.е. две строки (столбца) матрицы линейно зависимы, а значит её определитель равен , таким образом

такая матрица, согласно определению, является __вырожденной__.

In [24]:
print("Проверим с помощью numpy")
arr=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(arr)

Проверим с помощью numpy


0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение:__<br>
<p></p>
a)Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:</br>

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

Из первой строки вычтем вторую и поменяем строки местами:

$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$

Ранг матрицы равен - 2

Проверим:

In [25]:
arr=([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(arr)

2

б)

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первой и второй строки, отбрасываем:

$\begin{pmatrix}
0 & 0 & 2&1\\ 
0& 0 & 2&2\\
2&3&5&6
\end{pmatrix}$

Вычтем вторую строку из первой:

$\begin{pmatrix}
0 & 0 & 0&-1\\ 
0& 0 & 2&2\\
2&3&5&6
\end{pmatrix}$

Удалим второй столбец, который можно выразить через первый:

$\begin{pmatrix}
 0 & 0&-1\\ 
 0 & 2& 2\\
 2&5&6
\end{pmatrix}$

Поменяем местами первую и третью строки:

$\begin{pmatrix}
 2 & 5&6\\ 
 0 & 2& 2\\
 0&0& -1
\end{pmatrix}$

Ранг матрицы равен 

Проверим: 3




In [26]:
arr=([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(arr)

3

Ранк матрицы равен 3.